/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_cs_ark_ad3_AD3Jni */

#ifndef _Included_edu_cmu_cs_ark_ad3_AD3Jni
#define _Included_edu_cmu_cs_ark_ad3_AD3Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    BinaryVariable_GetLogPotential
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_BinaryVariable_1GetLogPotential
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    BinaryVariable_SetLogPotential
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_BinaryVariable_1SetLogPotential
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    BinaryVariable_GetId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_BinaryVariable_1GetId
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    BinaryVariable_Degree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_BinaryVariable_1Degree
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    MultiVariable_GetNumStates
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_MultiVariable_1GetNumStates
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    MultiVariable_GetState
 * Signature: (I)Ledu/cmu/cs/ark/ad3/BinaryVariable;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_MultiVariable_1GetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    MultiVariable_GetLogPotential
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_MultiVariable_1GetLogPotential
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    MultiVariable_SetLogPotential
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_MultiVariable_1SetLogPotential
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_GetAdditionalLogPotentials
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1GetAdditionalLogPotentials
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_SetAdditionalLogPotentials
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1SetAdditionalLogPotentials
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_Degree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1Degree
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_GetLinkId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1GetLinkId
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_GetVariable
 * Signature: (I)Ledu/cmu/cs/ark/ad3/BinaryVariable;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1GetVariable
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    Factor_SolveMap
 * Signature: ([D[D[D[DD)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_Factor_1SolveMap
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SetVerbosity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SetVerbosity
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SetEtaPSDD
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SetEtaPSDD
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SetMaxIterationsPSDD
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SetMaxIterationsPSDD
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SolveLPMAPWithPSDD
 * Signature: ([D[DD)I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SolveLPMAPWithPSDD
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SetEtaAD3
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SetEtaAD3
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_AdaptEtaAD3
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1AdaptEtaAD3
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SetMaxIterationsAD3
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SetMaxIterationsAD3
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_FixMultiVariablesWithoutFactors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1FixMultiVariablesWithoutFactors
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SolveLPMAPWithAD3
 * Signature: ([D[DD)I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SolveLPMAPWithAD3
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_SolveExactMAPWithAD3
 * Signature: ([D[DD)I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1SolveExactMAPWithAD3
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_GetDualVariables
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1GetDualVariables
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_GetLocalPrimalVariables
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1GetLocalPrimalVariables
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_GetGlobalPrimalVariables
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1GetGlobalPrimalVariables
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateBinaryVariable
 * Signature: ()Ledu/cmu/cs/ark/ad3/BinaryVariable;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateBinaryVariable
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateMultiVariable
 * Signature: (I)Ledu/cmu/cs/ark/ad3/MultiVariable;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateMultiVariable
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorDense
 * Signature: ([Ledu/cmu/cs/ark/ad3/MultiVariable;[DZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorDense
  (JNIEnv *, jobject, jobjectArray, jdoubleArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorXOR
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorXOR
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorXOROUT
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorXOROUT
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorAtMostOne
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorAtMostOne
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorOR
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorOR
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorOROUT
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorOROUT
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorANDOUT
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorANDOUT
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorIMPLY
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorIMPLY
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorPAIR
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;DZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorPAIR
  (JNIEnv *, jobject, jobjectArray, jdouble, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorBUDGET
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[ZIZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorBUDGET
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jint, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_CreateFactorKNAPSACK
 * Signature: ([Ledu/cmu/cs/ark/ad3/BinaryVariable;[Z[DDZ)Ledu/cmu/cs/ark/ad3/Factor;
 */
JNIEXPORT jobject JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1CreateFactorKNAPSACK
  (JNIEnv *, jobject, jobjectArray, jbooleanArray, jdoubleArray, jdouble, jboolean);

/*
 * Class:     edu_cmu_cs_ark_ad3_AD3Jni
 * Method:    FactorGraph_DeclareFactor
 * Signature: (Ledu/cmu/cs/ark/ad3/Factor;[Ledu/cmu/cs/ark/ad3/BinaryVariable;Z)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_cs_ark_ad3_AD3Jni_FactorGraph_1DeclareFactor
  (JNIEnv *, jobject, jobject, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
